server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /qr/ {
        alias /static/;
        expires 7d;
    }
}
